name: Build ZIP as APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Zip Files and Rename to APK
      run: |
        sudo apt-get update && sudo apt-get install -y zip
        zip -r rebuilt_unsigned.zip .
        mv rebuilt_unsigned.zip rebuilt_unsigned.apk

    - name: Sign APK
      run: |
        # Added -dname to prevent interactive prompts from crashing the workflow
        keytool -genkey -v -keystore debug.jks -keyalg RSA -keysize 2048 -validity 10000 -alias debugalias -storepass password123 -keypass password123 -dname "CN=Anshu, OU=Hunter, O=Dev, L=Unknown, ST=Unknown, C=IN"
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore debug.jks rebuilt_unsigned.apk debugalias -storepass password123

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: final-signed-apk
        path: rebuilt_unsigned.apk
